import React from "react";
import Register from "@/components/templates/Login-Register/Register/Register";

export const metadata = {
  title: 'صفحه ثبت نام',
  description: 'Generated by Next.js',
}

export default function page() {
  return (
    <div className="relative w-full h-dvh  flex">
      <img src="/img/login.jpg" className="w-full h-full" alt="login image" />
      <div className="absolute w-1/2 left-0">
        <div className="relative  h-dvh bg-black opacity-50 ">
        </div>
          <Register />
      </div>
    </div>
  );
}
